# Generated by Django 4.0.4 on 2022-06-03 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessvaluation',
            name='price_close',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StockValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_value_max', models.FloatField()),
                ('book_value_min', models.FloatField()),
                ('book_value_avg', models.FloatField()),
                ('book_value_upsize', models.FloatField()),
                ('earnings_per_share_max', models.FloatField()),
                ('earnings_per_share_min', models.FloatField()),
                ('earnings_per_share_avg', models.FloatField()),
                ('earnings_per_share_upsize', models.FloatField()),
                ('enterprise_value_max', models.FloatField()),
                ('enterprise_value_min', models.FloatField()),
                ('enterprise_value_avg', models.FloatField()),
                ('enterprise_value_upsize', models.FloatField()),
                ('ev_over_ebit_max', models.FloatField()),
                ('ev_over_ebit_min', models.FloatField()),
                ('ev_over_ebit_avg', models.FloatField()),
                ('ev_over_ebit_upsize', models.FloatField()),
                ('ev_over_ebitda_max', models.FloatField()),
                ('ev_over_ebitda_min', models.FloatField()),
                ('ev_over_ebitda_avg', models.FloatField()),
                ('ev_over_ebitda_upsize', models.FloatField()),
                ('ev_sales_max', models.FloatField()),
                ('ev_sales_min', models.FloatField()),
                ('ev_sales_avg', models.FloatField()),
                ('ev_sales_upsize', models.FloatField()),
                ('price_to_book_max', models.FloatField()),
                ('price_to_book_min', models.FloatField()),
                ('price_to_book_avg', models.FloatField()),
                ('price_to_book_upsize', models.FloatField()),
                ('price_earnings_max', models.FloatField()),
                ('price_earnings_min', models.FloatField()),
                ('price_earnings_avg', models.FloatField()),
                ('price_earnings_upsize', models.FloatField()),
                ('price_to_sales_max', models.FloatField()),
                ('price_to_sales_min', models.FloatField()),
                ('price_to_sales_avg', models.FloatField()),
                ('price_to_sales_upsize', models.FloatField()),
                ('market_cap_max', models.BigIntegerField()),
                ('market_cap_min', models.BigIntegerField()),
                ('market_cap_avg', models.FloatField()),
                ('market_cap_upsize', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_api.company')),
            ],
        ),
    ]
