# Generated by Django 4.0.4 on 2022-05-17 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('symbol', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('industry_name', models.CharField(max_length=2048)),
                ('floor_code', models.CharField(max_length=3)),
                ('company_name', models.CharField(max_length=2048)),
                ('shares_outstanding', models.BigIntegerField()),
                ('dividend_payout_ratio', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_symbol', models.CharField(max_length=10)),
                ('trading_date', models.DateTimeField()),
                ('price_high', models.FloatField()),
                ('price_low', models.FloatField()),
                ('price_open', models.FloatField()),
                ('price_close', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_date', models.DateTimeField()),
                ('price_high', models.FloatField()),
                ('price_low', models.FloatField()),
                ('price_open', models.FloatField()),
                ('price_close', models.FloatField()),
                ('total_volume', models.BigIntegerField()),
                ('total_value', models.BigIntegerField()),
                ('buy_foreign_value', models.BigIntegerField()),
                ('sell_foreign_value', models.BigIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_api.company')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField(max_length=1)),
                ('long_term_financial_assets', models.BigIntegerField()),
                ('net_revenue', models.BigIntegerField()),
                ('net_profit', models.BigIntegerField()),
                ('profit_before_taxes', models.BigIntegerField()),
                ('profit_after_taxes', models.BigIntegerField()),
                ('inventory', models.BigIntegerField()),
                ('liabilities', models.BigIntegerField()),
                ('receivables', models.BigIntegerField()),
                ('fixed_assets', models.BigIntegerField()),
                ('cash_equivalents', models.BigIntegerField()),
                ('total_assets', models.BigIntegerField()),
                ('equity', models.BigIntegerField()),
                ('authorized_capital', models.BigIntegerField()),
                ('short_term_assets', models.BigIntegerField()),
                ('short_term_liabilities', models.BigIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_api.company')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField(max_length=1)),
                ('return_on_sales', models.FloatField()),
                ('return_on_equity', models.FloatField()),
                ('return_on_assets', models.FloatField()),
                ('return_on_investments', models.FloatField()),
                ('return_on_invested_capitals', models.FloatField()),
                ('current_ratio', models.FloatField()),
                ('quick_ratio', models.FloatField()),
                ('cash_ratio', models.FloatField()),
                ('interest_coverage_ratio', models.FloatField()),
                ('inventory_turnover_ratio', models.FloatField()),
                ('receivable_turnover_ratio', models.FloatField()),
                ('debt_equity_ratio', models.FloatField()),
                ('equity_multiplier_ratio', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_api.company')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField(max_length=1)),
                ('earnings_per_share', models.FloatField()),
                ('enterprise_value', models.FloatField()),
                ('ev_over_ebit', models.FloatField()),
                ('ev_over_ebitda', models.FloatField()),
                ('ev_sales', models.FloatField()),
                ('price_to_book', models.FloatField()),
                ('price_earnings', models.FloatField()),
                ('price_to_sales', models.FloatField()),
                ('market_cap', models.BigIntegerField()),
                ('discounted_cash_flow', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_api.company')),
            ],
        ),
    ]
