# Generated by Django 4.0.4 on 2022-05-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessvaluation',
            name='quarter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='floor_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='financialratio',
            name='quarter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='quarter',
            field=models.IntegerField(),
        ),
    ]
