# Generated by Django 4.0.4 on 2022-05-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0002_alter_businessvaluation_quarter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='dividend_payout_ratio',
            field=models.BigIntegerField(null=True),
        ),
    ]
