# Generated by Django 4.0.4 on 2022-05-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0003_alter_company_dividend_payout_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='symbol',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
