# Generated by Django 4.0.4 on 2022-05-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0004_alter_company_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry_name',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
