# Generated by Django 4.0.4 on 2022-05-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0005_alter_company_industry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='total_value',
            field=models.BigIntegerField(null=True),
        ),
    ]
