# Generated by Django 4.0.4 on 2022-05-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0008_alter_stockprice_total_value'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='marketprice',
            index=models.Index(fields=['trading_date'], name='stock_api_m_trading_3835c7_idx'),
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['trading_date'], name='stock_api_s_trading_455a9e_idx'),
        ),
    ]
