# Generated by Django 4.0.4 on 2022-05-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0009_marketprice_stock_api_m_trading_3835c7_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockprice',
            unique_together={('company', 'trading_date')},
        ),
    ]
